sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=8716d5cc712bce305c93196cdd001da60ba480db713f99e7ad6240c7a2fc01e3
language: ruby
rvm:
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
